###
POST http://localhost:5001/author
Content-Type: application/json

{
    "name": "Patrizia",
    "surname": "Patti",
    "email": "patriziapatti@gmail.com",
    "password": "patriziapatti",
    "birthDate": 551334800000,
    "avatar": ""
}

###
GET http://localhost:5001/author?page=2&perPage=1

###
GET http://localhost:5001/author/66d321075e8ac74b71c6c49e

###
PUT http://localhost:5001/author/66d321075e8ac74b71c6c49e
Content-Type: application/json

{
    "email": "patrizia@gmail.com"
}

###
DELETE http://localhost:5001/author/66d321075e8ac74b71c6c49e