###
POST http://localhost:5001/api/v1/register
Content-Type: application/json

{
    "name": "Andrea",
    "surname": "Ruocco",
    "email": "ruoccoandrea@gmail.com",
    "password": "andrearuocco",
    "birthDate": 774032800000,
    "avatar": ""
}

###
POST http://localhost:5001/api/v1/login
Content-Type: application/json

{
    "email": "ruoccoandrea@gmail.com",
    "password": "andrearuocco"
}

###
GET http://localhost:5001/api/v1/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjY2ZDMyMDdkNWU4YWM3NGI3MWM2YzQ5YSIsImlhdCI6MTcyNTExMjQ4NiwiZXhwIjoxNzI1MTE2MDg2fQ.WEiwgY0WFsCyArdaSZVBTLoA6tgWZfL39DhAzvtdBVI