###
POST http://localhost:5001/api/v1/register
Content-Type: application/json

{
    "name": "michele",
    "surname": "Ruocco",
    "email": "ruoccomichele@gmail.com",
    "password": "joelruocco",
    "birthDate": 774032800000,
    "avatar": ""
}

###
POST http://localhost:5001/api/v1/login
Content-Type: application/json

{
    "email": "paologmail@gmail.com",
    "password": "paologmail"
}

###
GET http://localhost:5001/api/v1/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JJZCI6IjY2ZDU3Mjk2MjQ0NGQxOWYwOWMwYzM1NSIsImlhdCI6MTcyNTI2ODEyMSwiZXhwIjoxNzI1MjcxNzIxfQ.Lw7T3bBURjCIHDwTEoMg8csRVQf82iguop29rd68aAE