###
POST http://localhost:5001/blogpost
Content-Type: application/json

{
    "category": "Category2",
    "title": "L'Italia contemporanea",
    "readTime": {
        "value": 36,
        "unit": "sec"
    },
    "author":  "66d572962444d19f09c0c355",
    "content": "This is the content of my awesome blog post.",
    "tags": [
        {"name": "history"},
        {"name": "politics scienze"}
    ]
}

###
GET http://localhost:5001/blogpost?page=1&perPage=1

###
GET http://localhost:5001/blogpost?title=italia

###
GET http://localhost:5001/blogpost/66d4d8d804d0e389a5080695

###
PUT http://localhost:5001/blogpost/66d4d8d804d0e389a5080695
Content-Type: application/json

{
    "title": "My blogPost"
}

###
DELETE http://localhost:5001/blogpost/66d3242e89b3d9ed5efac5ea

###
POST http://localhost:5001/blogpost/66dcae230fcf92a55fbb58d2/comments
Content-Type: application/json

{
    "author": "66dcae100fcf92a55fbb58cb",
    "content": "Lorem Ipsum è un testo segnaposto utilizzato anche dai developer bravi o meno bravi"
}

###
GET http://localhost:5001/blogpost/66dcae230fcf92a55fbb58d2/comments

###
GET http://localhost:5001/blogpost/66dcae230fcf92a55fbb58d2/comments/66dcae760fcf92a55fbb58db

###
PUT http://localhost:5001/blogpost/66dc7762b84a479dcc2cca7e/comment/66dc77acb84a479dcc2cca87
Content-Type: application/json

{
    "content": "Lorem Ipsum è un testo "
} 

###
DELETE http://localhost:5001/blogpost/66dc7762b84a479dcc2cca7e/comment/66dc77acb84a479dcc2cca87



