###
POST http://localhost:5001/blogpost
Content-Type: application/json

{
    "category": "Category2",
    "title": "L'Italia contemporanea",
    "readTime": {
        "value": 36,
        "unit": "sec"
    },
    "author": {
        "_id": "66d3207d5e8ac74b71c6c49a",
        "email": "ruoccoandrea@gmail.com"
    },
    "content": "This is the content of my awesome blog post.",
    "tags": [
        {"name": "history"},
        {"name": "politics scienze"}
    ]
}

###
GET http://localhost:5001/blogpost?page=1&perPage=1

###
GET http://localhost:5001/blogpost?title=post

###
GET http://localhost:5001/blogpost/66d321d5d97567c70e04e3a6

###
PUT http://localhost:5001/blogpost/66d3242e89b3d9ed5efac5ea
Content-Type: application/json

{
    "title": "My blogPost"
}

###
DELETE http://localhost:5001/blogpost/66d3242e89b3d9ed5efac5ea

###
POST http://localhost:5001/blogpost/66d321d5d97567c70e04e3a6/comments
Content-Type: application/json

{
    "content": "Lorem Ipsum è un testo segnaposto utilizzato anche dai developer bravi o meno bravi"
}

###
GET http://localhost:5001/blogpost/66d321d5d97567c70e04e3a6/comments

###
GET http://localhost:5001/blogpost/66d321d5d97567c70e04e3a6/comments/66d32801079e900f68090ab1

###
PUT http://localhost:5001/blogpost/66d321d5d97567c70e04e3a6/comment/66d32801079e900f68090ab1
Content-Type: application/json

{
    "content": "Lorem Ipsum è un testo segnaposto utilizzato anche dai devoloper non bravi"
} 

###
DELETE http://localhost:5001/blogpost/66d321d5d97567c70e04e3a6/comment/66d32823079e900f68090ab3



