###
POST http://localhost:5001/api/v1/register
Content-Type: application/json

{
    "name": "Andrea",
    "surname": "Teppista",
    "email": "ciaomonGodb@gmail.com",
    "password": "attivandalici"
}

###
POST http://localhost:5001/api/v1/login
Content-Type: application/json

{
    "email": "ciaomonGodb@gmail.com",
    "password": "attivandalici"
}